name: cat_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.7

  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  firebase_auth: ^5.4.1
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  flutter_launcher_icons: ^0.14.3
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  sqflite: ^2.4.1
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/cat_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/cat_icon.png
