// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTMkDEzEHsmxRCAV-EECLEfr74fqwqLmo',
    appId: '1:361062371431:web:af18000ce19f321d33c4c2',
    messagingSenderId: '361062371431',
    projectId: 'cat-app-1cbaa',
    authDomain: 'cat-app-1cbaa.firebaseapp.com',
    storageBucket: 'cat-app-1cbaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtU3TRfCgjL88ofxSrqC3jZxpru4E2Itw',
    appId: '1:361062371431:android:9fe5e8f1b00c0ae433c4c2',
    messagingSenderId: '361062371431',
    projectId: 'cat-app-1cbaa',
    storageBucket: 'cat-app-1cbaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNh023rtLDDT9nPC3mc5sJj3dJ7ADTVE',
    appId: '1:361062371431:ios:0be5ae54a2bfa4de33c4c2',
    messagingSenderId: '361062371431',
    projectId: 'cat-app-1cbaa',
    storageBucket: 'cat-app-1cbaa.firebasestorage.app',
    iosBundleId: 'com.example.catApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFNh023rtLDDT9nPC3mc5sJj3dJ7ADTVE',
    appId: '1:361062371431:ios:0be5ae54a2bfa4de33c4c2',
    messagingSenderId: '361062371431',
    projectId: 'cat-app-1cbaa',
    storageBucket: 'cat-app-1cbaa.firebasestorage.app',
    iosBundleId: 'com.example.catApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTMkDEzEHsmxRCAV-EECLEfr74fqwqLmo',
    appId: '1:361062371431:web:9fa4f8209e10141333c4c2',
    messagingSenderId: '361062371431',
    projectId: 'cat-app-1cbaa',
    authDomain: 'cat-app-1cbaa.firebaseapp.com',
    storageBucket: 'cat-app-1cbaa.firebasestorage.app',
  );
}
